spring:
  application:
    name: commit-graph
  datasource:
      url: jdbc:postgresql://localhost:22321/postgres
      username: postgres
      password: postgres
  jpa:
    open-in-view: false
server:
  port: 8000
github:
  api:
    token: put-your-github-token
