spring:
  application:
    name: commit-graph
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
server:
  port: 8000
github:
  api:
    token: ${GITHUB_API_TOKEN}
